name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - 'development'
      - 'testing'
  push:
    branches:
      - 'development'
      - 'testing'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build production application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ap-southeast-2'
      DEV_CLOUDFRONT_ID: ${{ secrets.DEV_CLOUDFRONT_ID }}
      SIT_CLOUDFRONT_ID: ${{ secrets.SIT_CLOUDFRONT_ID }}
      
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/development'
        run: |
          aws s3 sync ./dist/ s3://todolist-dev --delete
          aws cloudfront create-invalidation --distribution-id ${{ env.DEV_CLOUDFRONT_ID }} --paths "/*"

      - name: Deploy to SIT
        if: github.ref == 'refs/heads/testing'
        run: |
          aws s3 sync ./dist/ s3://todolist-sit --delete
          aws cloudfront create-invalidation --distribution-id ${{ env.SIT_CLOUDFRONT_ID }} --paths "/*"